### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by aquilax** [google/songbird#12]
I am getting:
```js
songbird.min.js:1 Uncaught SyntaxError: Identifier 'n' has already been declared
    at songbird.min.js:1
    at songbird.min.js:1
(anonymous) @ songbird.min.js:1
(anonymous) @ songbird.min.js:1
panner-node-vs-songbird.js:97 Uncaught ReferenceError: Songbird is not defined
    at onLoad (panner-node-vs-songbird.js:97)
onLoad @ panner-node-vs-songbird.js:97
```
on https://cdn.rawgit.com/google/songbird/master/examples/panner-node-vs-songbird.html
with Chrome Version 61.0.3163.100 (Official Build) (64-bit) on Windows/

**Comment by drewbitllama** [comment]
Thank you! I've updated the repo to fix the merge conflicts. The CDN link will hopefully be updated to reflect the changes within the hour.
