### ISSUE TITLE
mobile browser support

### ISSUE THREAD

**Issue by dylancarlone** [google/songbird#2]
Any plans to support songbird on mobile browsers?

**Comment by mrdoob** [comment]
This example works on Chrome/Android: 
https://cdn.rawgit.com/google/songbird/master/examples/webgl-demo.html

**Comment by dylancarlone** [comment]
My mistake, I only tested it on Safari. What's keeping it from working?

**Comment by drewbitllama** [comment]
Hi Dylan,

Currently, we need to enable Safari/iOS support for Omnitone and at that point we will be able to offer similar support for Songbird.

Cheers,
Drew

**Comment by dylancarlone** [comment]
Great, I'll keep an eye out. Thanks!
