### ISSUE TITLE
Is there a simple way to transition between positions on click?

### ISSUE THREAD

**Issue by johnsmith1243** [google/songbird#7]
I have a button which changes the position of an audio file on click: 
`<button class="change" onclick="changeposition();">change position</button>` 
The function is this:
`	function changeposition() {
	source.setPosition(-2, 8.9, 0); }`

Is there a simple way to transition between these positions onclick? For example, so that the audio would transition to the new position over the course of a second, rather than jump to the position?

     let audioContext = new AudioContext();
    // Create a (1st-order Ambisonic) Songbird scene.
    let songbird = new Songbird(audioContext);
    // Send songbird's binaural output to stereo out.
    songbird.output.connect(audioContext.destination);

    // Set room acoustics properties.
    let dimensions = {
      width : 4,
      height : 2.5,
      depth : 3
    };
    let materials = {
      left : 'plaster-rough',
      right : 'plaster-rough',
      front : 'glass-thick',
      back : 'plaster-rough',
      down : 'plywood-panel',
      up : 'plaster-rough'
    };
    songbird.setRoomProperties(dimensions, materials);

    // Create an audio element. Feed into audio graph.
    let audioElement = document.createElement('audio');
    audioElement.src = 'sound.mp3';
	

    let audioElementSource =
      audioContext.createMediaElementSource(audioElement);

    // Create a Source, connect desired audio input to it.
    let source = songbird.createSource();
    audioElementSource.connect(source.input);

    // The source position is relative to the origin
    // (center of the room).
    source.setPosition(0.0, 8.9, 0);

    // Playback the audio.
    audioElement.play(); 
	audioElement.loop = true;
	
	function changeposition() {
	source.setPosition(-2, 8.9, 0);}

**Comment by drewbitllama** [comment]
Hey John,

This might actually be a neat feature to consider for an upcoming release
(I'll consider adding an optional delay parameter to setPosition to do
this), but in the meantime, what you'd want to do is create a interval
callback function that slowly increments an interpolation value and use
that to interpolate between current and next position:

Keep in mind there may be several ways you wish to smoothly move from point
to point, this will only allow movement with continuous speed in straight
lines. If you want your object to move in a curve, you'll need to design
something a bit fancier.

Let me know if you have any questions!

Cheers,
Drew

let currentPosition = [1, 2, 3];
let nextPosition = [4, 5, 6];
let alpha = 0;
let intervalSeconds = 0.01; // 10ms update rate.

function interpolatePosition() {
  alpha += intervalSeconds;
  let position = [];
  for (let i = 0; i < 3; i++) {
    position[i] = (1 - alpha) * currentPosition[i] + alpha *
nextPosition[i];
  }
  source.setPosition(position[0], position[1], position[2]);
}

window.setInterval(interpolatePosition, intervalSeconds * 1000); // Convert
interval to milliseconds.

**Comment by johnsmith1243** [comment]
Hi, thanks a lot for your response. 
I'm new to this and having a lot of trouble figuring out how to integrate the code you posted.   I changed my code a bit so I can use more than one sound, and im not sure where the code you sent me should fit in. Could you point me in the right direction? Here is my new code:

`    <button onclick="play1()">play 1</button>
    <button onclick="mySource.setPosition(-0.9, 8.9, 0)">position 1</button>
    <button onclick="mySource.setPosition(-2, 8.9, -1)">position 2</button>
	
	<button onclick="play2()">play 2</button>
    <button onclick="mySource2.setPosition(-0.9, 8.9, 0)">position 1</button>
    <button onclick="mySource2.setPosition(-2, 8.9, -1)">position 2</button>
	

	let mySource;
    function play(audioSource) {
      let audioContext = new AudioContext();
      // Create a (1st-order Ambisonic) Songbird scene.
      let songbird = new Songbird(audioContext);
      // Send songbird's binaural output to stereo out.
      songbird.output.connect(audioContext.destination);
      // Set room acoustics properties.
      let dimensions = {
        width : 4,
        height : 2.5,
        depth : 3
      };
      let materials = {
        left : 'plaster-rough',
        right : 'plaster-rough',
        front : 'plaster-rough',
        back : 'plaster-rough',
        down : 'plywood-panel',
        up : 'plaster-rough'
      };
      songbird.setRoomProperties(dimensions, materials);
      // Create an audio element. Feed into audio graph.
      let audioElement = document.createElement('audio');
      audioElement.src = audioSource;
      let audioElementSource =
      audioContext.createMediaElementSource(audioElement);
      // Create a Source, connect desired audio input to it.
      let source = songbird.createSource();
      audioElementSource.connect(source.input);

      // The source position is relative to the origin
      // (center of the room).
      source.setPosition(0.0, 8.9, 0);
      // Playback the audio.
      audioElement.play();
      audioElement.loop = true;
 
      return source;
    }
    function sound1() {
      mySource = play('sound1.ogg')
    }
 

let mySource2;
function play2(audioSource) {
      let audioContext = new AudioContext();
      // Create a (1st-order Ambisonic) Songbird scene.
      let songbird = new Songbird(audioContext);
      // Send songbird's binaural output to stereo out.
      songbird.output.connect(audioContext.destination);
      // Set room acoustics properties.
      let dimensions = {
        width : 4,
        height : 2.5,
        depth : 3
      };
      let materials = {
        left : 'plaster-rough',
        right : 'plaster-rough',
        front : 'plaster-rough',
        back : 'plaster-rough',
        down : 'plywood-panel',
        up : 'plaster-rough'
      };
      songbird.setRoomProperties(dimensions, materials);
      // Create an audio element. Feed into audio graph.
      let audioElement = document.createElement('audio');
      audioElement.src = audioSource;
      let audioElementSource =
      audioContext.createMediaElementSource(audioElement);
      // Create a Source, connect desired audio input to it.
      let source2 = songbird.createSource();
      audioElementSource.connect(source2.input);
      // The source position is relative to the origin
      // (center of the room).
      source2.setPosition(-3, 8.9, 0);
      // Playback the audio.
      audioElement.play();
 
      return source2;
	  }
	   function sound2() {
      mySource2 = play2('sound2.ogg')
		}`

**Comment by drewbitllama** [comment]
Hi John,

Consult the room model example to see how to handle multiple sources using
the same songbird instance. This will be far more efficient and cleaner
code. Also, consult the birds example for more information on multiple
automated moving sources.

Cheers,
Drew
